[project]
name = "python-ivi"
version = "0.1.0"
description = "Python Interchangeable Virtual Instrument Library"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.9.5",
]
